<a href="https://colab.research.google.com/github/pawel0508/First_repository/blob/master/%C4%86wiczenie_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.18.5'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [7]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate((A, B), axis = 0) # tablice podawać w tupli 

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [8]:
np.concatenate((A, B), axis = 1) # tablice podawać w tupli

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [9]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
np.concatenate((data, target), axis = 1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [10]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
# przekształcamy 
np.column_stack((feature1, feature2, feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [32]:
A = np.array([[0, 0, 4, 6, 2, 4, 1, 1],
              [0, 0, 6, 2, 2, 4, 1, 1],
              [0, 0, 1, 3, 5, 5, 1, 1],
              [0, 0, 3, 1, 5, 4, 1, 1],
              [0, 0, 2, 6, 1, 3, 1, 1]])
A1, A2, A3 = np.split(A, indices_or_sections = [2, 6], axis = 1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [35]:
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A)

24

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [37]:
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A, axis= 1) # axis = 1

array([3, 1, 2, 2, 3, 5, 4, 2, 2, 4])

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [38]:
A = np.random.randn(10, 4)
np.set_printoptions(precision=4)
print(A)

[[-0.1924  0.3015 -0.0347 -1.1687]
 [ 1.1428  0.7519  0.791  -0.9094]
 [ 1.4028 -1.4019  0.5869  2.1905]
 [-0.9905 -0.5663  0.0997 -0.5035]
 [-1.5507  0.0686 -1.0623  0.4736]
 [-0.9194  1.5499 -0.7833 -0.3221]
 [ 0.8135 -1.2309  0.2275  1.3071]
 [-1.6075  0.1846  0.2599  0.7818]
 [-1.237  -1.3205  0.5219  0.297 ]
 [ 0.2505  0.3464 -0.68    0.2323]]


### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [40]:
A = np.array([1.2e-6, 1.7e-7])
np.set_printoptions(precision=8, suppress=True)
print(A)

[0.0000012  0.00000017]


### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [43]:
A = np.random.randn(8, 4)
np.delete(A, [3], axis = 1)

array([[-0.48536355,  0.08187414,  2.31465857],
       [ 0.68626019, -1.61271587, -0.47193187],
       [ 0.06428002, -1.07774478, -0.71530371],
       [-0.73036663,  0.21645859,  0.04557184],
       [ 2.14394409,  0.63391902, -2.02514259],
       [-0.66178646,  0.85243333, -0.79252074],
       [ 0.50498728,  0.86575519, -1.20029641],
       [-0.47494531, -0.65332923,  1.76545424]])

### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [48]:
v = np.array([3, 4, -2])
np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [52]:
A = np.random.randint(10, size=(100, 30))
np.set_printoptions(edgeitems = 10)
print(A)

[[5 6 1 7 4 6 0 4 0 7 ... 9 0 3 6 5 9 0 0 7 3]
 [4 6 7 9 6 1 3 9 0 9 ... 1 0 1 7 8 1 6 4 2 8]
 [5 0 4 6 3 7 9 4 8 8 ... 8 5 3 3 2 6 2 1 9 7]
 [3 7 0 4 8 0 3 5 9 7 ... 1 2 3 3 7 0 9 3 3 0]
 [2 4 5 8 8 8 0 8 7 1 ... 2 5 7 2 9 8 9 4 6 7]
 [2 1 1 4 0 1 8 6 5 8 ... 7 4 8 2 2 0 8 5 1 7]
 [8 8 1 1 6 3 0 7 1 2 ... 1 6 4 5 0 6 5 3 0 8]
 [3 1 7 1 4 5 7 0 0 3 ... 8 2 4 1 9 4 7 1 7 3]
 [9 9 0 4 0 6 7 2 2 6 ... 9 8 2 2 3 0 8 2 9 3]
 [0 3 0 4 4 6 7 3 6 3 ... 6 5 9 1 2 1 2 0 7 5]
 ...
 [3 7 1 6 3 1 6 0 3 8 ... 2 2 1 4 9 2 2 7 3 3]
 [2 0 7 0 6 4 3 3 7 5 ... 1 4 5 4 2 3 6 3 8 9]
 [1 4 7 4 9 7 7 8 9 5 ... 7 5 3 8 4 9 5 8 6 4]
 [1 3 1 2 9 2 3 5 2 9 ... 1 7 6 5 4 3 6 2 7 1]
 [0 1 8 4 7 2 6 1 7 6 ... 8 3 4 7 0 0 8 8 3 1]
 [8 3 5 0 8 4 2 3 0 8 ... 9 3 1 8 3 7 1 7 9 4]
 [6 6 8 2 9 3 9 3 9 4 ... 6 0 4 9 5 4 3 0 6 8]
 [5 2 9 3 9 4 0 4 0 8 ... 5 4 1 7 6 5 4 4 8 0]
 [8 5 3 9 6 8 4 4 7 6 ... 9 0 7 1 0 7 1 5 5 4]
 [7 2 9 3 6 6 7 1 1 3 ... 5 2 9 8 5 3 3 7 6 0]]
